# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo $JAVA_HOME
      echo $(jdk_version)
      java -version
      mvn --version

- task: Maven@3
  inputs:
    mavenPomFile: './pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/src/test/java/avfranco_br/TEST-*.xml'
    testRunTitle: './src/test/java/avfranco_br/dsaTest.java'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    goals: 'package'
    
- task: Bash@3
  condition: succeeded()
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo 'Display DSA BST output'
      java -cp target/data-structures-algorithms-0.3-SNAPSHOT.jar avfranco_br.DataStructuresAlgorithms
      